name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Information
        run: |
          git rev-parse --short HEAD
          git describe --tags --exact-match || echo "No exact tag"
          git status

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/vehx35/testjupydoimages
          tags: |
            type=semver,pattern=v{{version}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/vehx35/testjupydoimages:latest
            ghcr.io/vehx35/testjupydoimages:${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
